In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#change path as per the local storage
df = pd.read_csv(r"C:\Users\sitan\OneDrive\Desktop\4th sem\4th sem\EDA\project\datasets\Crop_recommendation.csv")
df

In [ ]:
newColumns = ['label','N-max','N-min','P-max','P-min','K-max','K-min','temperature-max','temperature-min','ph-max','ph-min','rainfall-max','rainfall-min','humidity-min','humidity-max']

In [ ]:
df1 =df.groupby(['label'])['N','P','K','temperature','humidity','ph','rainfall'].min()
df1.rename(columns = {"N":'N-min',"P":"P-min","K":"K-min", "humidity":"humidity-min", "ph":"ph-min", "rainfall":"rainfall-min","temperature":"temperature-min"},inplace=True)

In [ ]:
df2=df.groupby(['label'])['N','P','K','temperature','humidity','ph','rainfall'].max()
df2.rename(columns = {"N":'N-max',"P":"P-max","K":"K-max", "humidity":"humidity-max", "ph":"ph-max", "rainfall":"rainfall-max","temperature":"temperature-max"},inplace=True)

In [107]:
df1

,N-min,P-min,K-min,temperature-min,humidity-min,ph-min,rainfall-min
label,,,,,,,
apple,0,120,195,21.036527,90.025751,5.514253,100.117344
banana,80,70,45,25.010185,75.031933,5.505394,90.109781
blackgram,20,55,15,25.097374,60.065349,6.500145,60.417903
chickpea,20,55,75,17.024985,14.258040,5.988993,65.113656
coconut,0,5,25,25.008724,90.017345,5.501580,131.090008
coffee,80,15,25,23.059519,50.045570,6.020947,115.156401
cotton,100,35,15,22.000851,75.005393,5.801048,60.653817
grapes,0,120,195,8.825675,80.016394,5.510925,65.010953
jute,60,35,35,23.094338,70.882596,6.002525,150.235524
kidneybeans,0,55,15,15.330426,18.092240,5.502999,60.275525
lentil,0,55,15,18.064861,60.091166,5.916454,35.034848
maize,60,35,15,18.041855,55.282204,5.513698,60.651715
mango,0,15,25,27.003155,45.022364,4.507524,89.291476
mothbeans,0,35,15,24.018254,40.009334,3.504752,30.920140
mungbean,0,35,15,27.014704,80.034996,6.218924,36.120429
muskmelon,80,5,45,27.024151,90.015064,6.002927,20.211267
orange,0,5,5,10.010813,90.006217,6.010392,100.173796
papaya,31,46,45,23.012402,90.038631,6.501521,40.351531
pigeonpeas,0,55,15,18.319104,30.400468,4.548202,90.054227
pomegranate,0,5,35,18.071330,85.129122,5.561852,102.518476
rice,60,35,35,20.045414,80.122675,5.005307,182.561632
watermelon,80,5,45,24.043558,80.026213,6.000976,40.126504

In [108]:
df2

,N-max,P-max,K-max,temperature-max,humidity-max,ph-max,rainfall-max
label,,,,,,,
apple,40,145,205,23.996862,94.920481,6.499227,124.983162
banana,120,95,55,29.908885,84.978492,6.490074,119.847970
blackgram,60,80,25,34.946616,69.961000,7.775306,74.915595
chickpea,60,80,85,20.995022,19.969789,8.868741,94.781896
coconut,40,30,35,29.869083,99.981876,6.470466,225.632366
coffee,120,40,35,27.923744,69.948073,7.493192,199.473564
cotton,140,60,25,25.992374,84.876690,7.994680,99.931008
grapes,40,145,205,41.948657,83.983517,6.499605,74.915062
jute,100,60,45,26.985822,89.891065,7.488014,199.836291
kidneybeans,40,80,25,24.923601,24.969699,5.998125,149.744103
lentil,40,80,25,29.944139,69.923759,7.841496,54.939377
maize,100,60,25,26.549864,74.829137,6.995844,109.751538
mango,40,40,35,35.990097,54.964053,6.967418,100.812466
mothbeans,40,60,25,31.999286,64.955854,9.935091,74.443307
mungbean,40,60,25,29.914544,89.996156,7.199495,59.872321
muskmelon,120,30,55,29.943492,94.962187,6.781050,29.866814
orange,40,30,15,34.906653,94.964199,7.995849,119.694658
papaya,70,70,55,43.675493,94.944821,6.993473,248.859299
pigeonpeas,40,80,25,36.977944,69.691413,7.445445,198.829881
pomegranate,40,30,45,24.962732,94.998975,7.199504,112.475094
rice,99,60,45,26.929951,84.969072,7.868475,298.560117
watermelon,120,30,55,26.986037,89.984052,6.956509,59.759800

In [ ]:
#need to merge the dataframes and make label a defined column as in groupby 
#the attribute used for group by isnt made into a column