In [2]:
import numpy as np
import pandas as pd

In [3]:
#change path as per the local storage
df = pd.read_csv(r"C:\Users\sitan\OneDrive\Desktop\4th sem\4th sem\EDA\project\datasets\Crop_recommendation.csv")
df

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [14]:
newColumns = ['N-max','N-min','P-max','P-min','K-max','K-min','temperature-max','temperature-min','ph-max','ph-min','rainfall-max','rainfall-min','humidity-max','humidity-min']

In [5]:
df1 =df.groupby(['label'])['N','P','K','temperature','humidity','ph','rainfall'].min()
df1.rename(columns = {"N":'N-min',"P":"P-min","K":"K-min", "humidity":"humidity-min", "ph":"ph-min", "rainfall":"rainfall-min","temperature":"temperature-min"},inplace=True)

<ipython-input-5-d66db4bb2467>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df1 =df.groupby(['label'])['N','P','K','temperature','humidity','ph','rainfall'].min()

In [6]:
df2=df.groupby(['label'])['N','P','K','temperature','humidity','ph','rainfall'].max()
df2.rename(columns = {"N":'N-max',"P":"P-max","K":"K-max", "humidity":"humidity-max", "ph":"ph-max", "rainfall":"rainfall-max","temperature":"temperature-max"},inplace=True)

<ipython-input-6-9ea16c812463>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df2=df.groupby(['label'])['N','P','K','temperature','humidity','ph','rainfall'].max()

In [7]:
df1

,N-min,P-min,K-min,temperature-min,humidity-min,ph-min,rainfall-min
label,,,,,,,
apple,0,120,195,21.036527,90.025751,5.514253,100.117344
banana,80,70,45,25.010185,75.031933,5.505394,90.109781
blackgram,20,55,15,25.097374,60.065349,6.500145,60.417903
chickpea,20,55,75,17.024985,14.258040,5.988993,65.113656
coconut,0,5,25,25.008724,90.017345,5.501580,131.090008
coffee,80,15,25,23.059519,50.045570,6.020947,115.156401
cotton,100,35,15,22.000851,75.005393,5.801048,60.653817
grapes,0,120,195,8.825675,80.016394,5.510925,65.010953
jute,60,35,35,23.094338,70.882596,6.002525,150.235524
kidneybeans,0,55,15,15.330426,18.092240,5.502999,60.275525
lentil,0,55,15,18.064861,60.091166,5.916454,35.034848
maize,60,35,15,18.041855,55.282204,5.513698,60.651715
mango,0,15,25,27.003155,45.022364,4.507524,89.291476
mothbeans,0,35,15,24.018254,40.009334,3.504752,30.920140
mungbean,0,35,15,27.014704,80.034996,6.218924,36.120429
muskmelon,80,5,45,27.024151,90.015064,6.002927,20.211267
orange,0,5,5,10.010813,90.006217,6.010392,100.173796
papaya,31,46,45,23.012402,90.038631,6.501521,40.351531
pigeonpeas,0,55,15,18.319104,30.400468,4.548202,90.054227
pomegranate,0,5,35,18.071330,85.129122,5.561852,102.518476
rice,60,35,35,20.045414,80.122675,5.005307,182.561632
watermelon,80,5,45,24.043558,80.026213,6.000976,40.126504

In [8]:
df2

,N-max,P-max,K-max,temperature-max,humidity-max,ph-max,rainfall-max
label,,,,,,,
apple,40,145,205,23.996862,94.920481,6.499227,124.983162
banana,120,95,55,29.908885,84.978492,6.490074,119.847970
blackgram,60,80,25,34.946616,69.961000,7.775306,74.915595
chickpea,60,80,85,20.995022,19.969789,8.868741,94.781896
coconut,40,30,35,29.869083,99.981876,6.470466,225.632366
coffee,120,40,35,27.923744,69.948073,7.493192,199.473564
cotton,140,60,25,25.992374,84.876690,7.994680,99.931008
grapes,40,145,205,41.948657,83.983517,6.499605,74.915062
jute,100,60,45,26.985822,89.891065,7.488014,199.836291
kidneybeans,40,80,25,24.923601,24.969699,5.998125,149.744103
lentil,40,80,25,29.944139,69.923759,7.841496,54.939377
maize,100,60,25,26.549864,74.829137,6.995844,109.751538
mango,40,40,35,35.990097,54.964053,6.967418,100.812466
mothbeans,40,60,25,31.999286,64.955854,9.935091,74.443307
mungbean,40,60,25,29.914544,89.996156,7.199495,59.872321
muskmelon,120,30,55,29.943492,94.962187,6.781050,29.866814
orange,40,30,15,34.906653,94.964199,7.995849,119.694658
papaya,70,70,55,43.675493,94.944821,6.993473,248.859299
pigeonpeas,40,80,25,36.977944,69.691413,7.445445,198.829881
pomegranate,40,30,45,24.962732,94.998975,7.199504,112.475094
rice,99,60,45,26.929951,84.969072,7.868475,298.560117
watermelon,120,30,55,26.986037,89.984052,6.956509,59.759800

In [9]:
df3 = pd.concat([df1,df2],axis = 1)
df3

,N-min,P-min,K-min,temperature-min,humidity-min,ph-min,rainfall-min,N-max,P-max,K-max,temperature-max,humidity-max,ph-max,rainfall-max
label,,,,,,,,,,,,,,
apple,0,120,195,21.036527,90.025751,5.514253,100.117344,40,145,205,23.996862,94.920481,6.499227,124.983162
banana,80,70,45,25.010185,75.031933,5.505394,90.109781,120,95,55,29.908885,84.978492,6.490074,119.847970
blackgram,20,55,15,25.097374,60.065349,6.500145,60.417903,60,80,25,34.946616,69.961000,7.775306,74.915595
chickpea,20,55,75,17.024985,14.258040,5.988993,65.113656,60,80,85,20.995022,19.969789,8.868741,94.781896
coconut,0,5,25,25.008724,90.017345,5.501580,131.090008,40,30,35,29.869083,99.981876,6.470466,225.632366
coffee,80,15,25,23.059519,50.045570,6.020947,115.156401,120,40,35,27.923744,69.948073,7.493192,199.473564
cotton,100,35,15,22.000851,75.005393,5.801048,60.653817,140,60,25,25.992374,84.876690,7.994680,99.931008
grapes,0,120,195,8.825675,80.016394,5.510925,65.010953,40,145,205,41.948657,83.983517,6.499605,74.915062
jute,60,35,35,23.094338,70.882596,6.002525,150.235524,100,60,45,26.985822,89.891065,7.488014,199.836291
kidneybeans,0,55,15,15.330426,18.092240,5.502999,60.275525,40,80,25,24.923601,24.969699,5.998125,149.744103
lentil,0,55,15,18.064861,60.091166,5.916454,35.034848,40,80,25,29.944139,69.923759,7.841496,54.939377
maize,60,35,15,18.041855,55.282204,5.513698,60.651715,100,60,25,26.549864,74.829137,6.995844,109.751538
mango,0,15,25,27.003155,45.022364,4.507524,89.291476,40,40,35,35.990097,54.964053,6.967418,100.812466
mothbeans,0,35,15,24.018254,40.009334,3.504752,30.920140,40,60,25,31.999286,64.955854,9.935091,74.443307
mungbean,0,35,15,27.014704,80.034996,6.218924,36.120429,40,60,25,29.914544,89.996156,7.199495,59.872321
muskmelon,80,5,45,27.024151,90.015064,6.002927,20.211267,120,30,55,29.943492,94.962187,6.781050,29.866814
orange,0,5,5,10.010813,90.006217,6.010392,100.173796,40,30,15,34.906653,94.964199,7.995849,119.694658
papaya,31,46,45,23.012402,90.038631,6.501521,40.351531,70,70,55,43.675493,94.944821,6.993473,248.859299
pigeonpeas,0,55,15,18.319104,30.400468,4.548202,90.054227,40,80,25,36.977944,69.691413,7.445445,198.829881
pomegranate,0,5,35,18.071330,85.129122,5.561852,102.518476,40,30,45,24.962732,94.998975,7.199504,112.475094
rice,60,35,35,20.045414,80.122675,5.005307,182.561632,99,60,45,26.929951,84.969072,7.868475,298.560117
watermelon,80,5,45,24.043558,80.026213,6.000976,40.126504,120,30,55,26.986037,89.984052,6.956509,59.759800

In [15]:
df3 =df3[newColumns]
df3

,N-max,N-min,P-max,P-min,K-max,K-min,temperature-max,temperature-min,ph-max,ph-min,rainfall-max,rainfall-min,humidity-max,humidity-min
label,,,,,,,,,,,,,,
apple,40,0,145,120,205,195,23.996862,21.036527,6.499227,5.514253,124.983162,100.117344,94.920481,90.025751
banana,120,80,95,70,55,45,29.908885,25.010185,6.490074,5.505394,119.847970,90.109781,84.978492,75.031933
blackgram,60,20,80,55,25,15,34.946616,25.097374,7.775306,6.500145,74.915595,60.417903,69.961000,60.065349
chickpea,60,20,80,55,85,75,20.995022,17.024985,8.868741,5.988993,94.781896,65.113656,19.969789,14.258040
coconut,40,0,30,5,35,25,29.869083,25.008724,6.470466,5.501580,225.632366,131.090008,99.981876,90.017345
coffee,120,80,40,15,35,25,27.923744,23.059519,7.493192,6.020947,199.473564,115.156401,69.948073,50.045570
cotton,140,100,60,35,25,15,25.992374,22.000851,7.994680,5.801048,99.931008,60.653817,84.876690,75.005393
grapes,40,0,145,120,205,195,41.948657,8.825675,6.499605,5.510925,74.915062,65.010953,83.983517,80.016394
jute,100,60,60,35,45,35,26.985822,23.094338,7.488014,6.002525,199.836291,150.235524,89.891065,70.882596
kidneybeans,40,0,80,55,25,15,24.923601,15.330426,5.998125,5.502999,149.744103,60.275525,24.969699,18.092240
lentil,40,0,80,55,25,15,29.944139,18.064861,7.841496,5.916454,54.939377,35.034848,69.923759,60.091166
maize,100,60,60,35,25,15,26.549864,18.041855,6.995844,5.513698,109.751538,60.651715,74.829137,55.282204
mango,40,0,40,15,35,25,35.990097,27.003155,6.967418,4.507524,100.812466,89.291476,54.964053,45.022364
mothbeans,40,0,60,35,25,15,31.999286,24.018254,9.935091,3.504752,74.443307,30.920140,64.955854,40.009334
mungbean,40,0,60,35,25,15,29.914544,27.014704,7.199495,6.218924,59.872321,36.120429,89.996156,80.034996
muskmelon,120,80,30,5,55,45,29.943492,27.024151,6.781050,6.002927,29.866814,20.211267,94.962187,90.015064
orange,40,0,30,5,15,5,34.906653,10.010813,7.995849,6.010392,119.694658,100.173796,94.964199,90.006217
papaya,70,31,70,46,55,45,43.675493,23.012402,6.993473,6.501521,248.859299,40.351531,94.944821,90.038631
pigeonpeas,40,0,80,55,25,15,36.977944,18.319104,7.445445,4.548202,198.829881,90.054227,69.691413,30.400468
pomegranate,40,0,30,5,45,35,24.962732,18.071330,7.199504,5.561852,112.475094,102.518476,94.998975,85.129122
rice,99,60,60,35,45,35,26.929951,20.045414,7.868475,5.005307,298.560117,182.561632,84.969072,80.122675
watermelon,120,80,30,5,55,45,26.986037,24.043558,6.956509,6.000976,59.759800,40.126504,89.984052,80.026213

In [17]:
label = pd.Series(df['label'])

0         rice
1         rice
2         rice
3         rice
4         rice
         ...
2195    coffee
2196    coffee
2197    coffee
2198    coffee
2199    coffee
Name: label, Length: 2200, dtype: object

In [33]:
label = pd.Series.drop_duplicates(label, keep='first', inplace=False,)
label.sort_values()
label

0              rice
100           maize
200        chickpea
300     kidneybeans
400      pigeonpeas
500       mothbeans
600        mungbean
700       blackgram
800          lentil
900     pomegranate
1000         banana
1100          mango
1200         grapes
1300     watermelon
1400      muskmelon
1500          apple
1600         orange
1700         papaya
1800        coconut
1900         cotton
2000           jute
2100         coffee
Name: label, dtype: object

In [32]:
df3.to_csv(r"C:\Users\sitan\OneDrive\Desktop\4th sem\4th sem\EDA\project1\cleanCrop2.csv")